### ISSUE TITLE
Hide/Reveal Text

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra-sui#2]
This is a cool little feature (and it might solve our difficulty in getting to a proper, yet playful slogan).

We should do it better though, and not with css display. Maybe @amitaibu wants to use Elm, or maybe there exists already a jQuery library that does what we need.

I'm picturing that you start with the long text, then hit the tl;dr button, and:

1. The short text highlights (with transition effect).
2. the remaining part of the long text fades.
3. the short text reorganizes into the shorter statement.

**Comment by amitaibu** [comment]
Sounds like jQuery and css transitions.
