### ISSUE TITLE
Update gulpfile to include bower components

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra-sui#34]
from #27 
> Can you please confirm

I'm having some problems with gulp with this repo - I think that it's because I have an older Jekyll version installed globally. I have only been able to serve locally using `bundle exec jekyll serve`

...anyway: just looking at the gulpfile.js, it seems like this job isn't being done. There's a gulp-bower node module that maybe helps?

**Comment by amitaibu** [comment]
We just need to make sure it's copied upon `gulp build`, as we do [here](https://github.com/Gizra/drupal-elm-starter/blob/5852cdcdb9674e950f681c79f2069874fd6d583b/client/gulpfile.js#L100-L105)
