### ISSUE TITLE
Add the Team info of all the people

### ISSUE THREAD

**Issue by amitaibu** [Gizra/gizra-sui#52]
I will go over with the non-devs and get their data into the Team's page Elm app. After that, we might ask the devs to provide PRs, or "worst case" we'll ask the Elmers to go with the rest of the devs .

This is for now the only blocker I know of for the deploy.

/cc @RachelBaram

**Comment by amitaibu** [comment]
@IshaDakota as a small experiment, could you try to add your "Attributes", into the Elm app, based on what you see [here](https://github.com/Gizra/gizra-sui/blob/819ed9a146aa6f6205fce47f025443bb82b7491f/team_app/src/Attribute/Model.elm#L4), and [here](https://github.com/Gizra/gizra-sui/blob/819ed9a146aa6f6205fce47f025443bb82b7491f/team_app/src/GizraTeam.elm#L8)

**Comment by RachelBaram** [comment]
@amitaibu Besides the missing pictures, I am not clear if or how you need my help with this.

**Comment by amitaibu** [comment]
Oh sorry, I meant for you just to be aware to the 

> This is for now the only blocker I know of for the deploy.
