### ISSUE TITLE
Blog Title ribbon should link back to blog landing page

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra-sui#61]
![i_shadowed_our_cto_for_a_day__and_this_is_what_i_learned](https://cloud.githubusercontent.com/assets/688507/22893644/e426301e-f1db-11e6-9d59-8f5fb86cfa0f.png)

**Comment by amitaibu** [comment]
Good idea, especially since it's already an `a` tag :)

https://github.com/Gizra/gizra-sui/commit/2f3bfa5a3cfaaea96db3965c1e792a7af2987445
