### ISSUE TITLE
Font inconsistencies

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra-sui#63]
This is probably more of a Meta issue that needs further review, but there a lot of font inconsistencies, particularly in the blog posts.

see for example lists:

![open_data_and_our_commit_ment_](https://cloud.githubusercontent.com/assets/688507/22893743/40d35a62-f1dc-11e6-88f9-430c9988efbe.png)

![elm_from_a_business_perspective](https://cloud.githubusercontent.com/assets/688507/22893768/524f99ea-f1dc-11e6-9670-d226f1cb552b.png)

**Comment by amitaibu** [comment]
![open_data_and_our_commit_ment_](https://cloud.githubusercontent.com/assets/125707/22897054/df1db660-f22a-11e6-8720-ee5e9ba2a9b7.jpg)

https://github.com/Gizra/gizra-sui/commit/52e243c3ae210181ecc0888f826fd1e5de639771

The second one was actually a bad formatting in the post

![elm_from_a_business_perspective](https://cloud.githubusercontent.com/assets/125707/22897087/047221c6-f22b-11e6-8956-f26939d46837.jpg)
