### ISSUE TITLE
Inconsistent height of blog cards on landing page

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra-sui#64]
Due to thumbnail image.

![gizra_s_blog](https://cloud.githubusercontent.com/assets/688507/22893910/bf6f1c62-f1dc-11e6-9404-1c309e1bf740.png)

**Comment by amitaibu** [comment]
The card height on the row is actually consistent. I've indeed noticed that specific row, but if you look at the one above it, the different image height IMO is nicer. We can address specifically this post, and reduce the thumb.

**Comment by amitaibu** [comment]
https://github.com/Gizra/gizra-sui/commit/e9dffc848c167ce01b6e0cf5601852387e5dc56d

![gizra_s_blog](https://cloud.githubusercontent.com/assets/125707/22896799/1a65a152-f22a-11e6-83a3-1599ecc7d443.jpg)
