### ISSUE TITLE
Contact form labels/placeholders

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra-sui#65]
forms should use labels or placeholders, not both.

![contact_us](https://cloud.githubusercontent.com/assets/688507/22894630/507f53c8-f1df-11e6-9817-e608bc5830e7.png)

**Comment by amitaibu** [comment]
Weird, I remember removing the placeholders! Anyway, properly removed now via https://github.com/Gizra/gizra-sui/commit/6390e53e9147a446b6da630143097195e7c18013

![contact_us](https://cloud.githubusercontent.com/assets/125707/22896427/b58db14e-f228-11e6-961f-7f3395440886.jpg)
