### ISSUE TITLE
Team page app: message covers selectable/unselectable labels

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra-sui#66]
Can't unselect and you are trapped.

![the_team](https://cloud.githubusercontent.com/assets/688507/22894763/c9264386-f1df-11e6-81bd-3bb548ff650f.png)

possible short term resolution is just to add some margin to the bottom of the header to give that area more play room.

**Comment by amitaibu** [comment]
https://github.com/Gizra/gizra-sui/commit/ba8cad2002164e6506f238899df100e8d7063cdc
