### ISSUE TITLE
Magnetic Labels language unclear

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/gizra-sui#67]
For instance, 

- "Nationality" could be "location" (maybe should be "is American", "is Israeli")
- "Language" could be "nationality" or "ethnicity" (maybe should be "speaks Russian")
- "Doing sports" should be "Playing Sports" (maybe?)
- we have no idea if comedy/drama/horror refers to movie genre, book genre, or ...

etc...

**Comment by amitaibu** [comment]
> "Doing sports" should be "Playing Sports" (maybe?)

I'll correct. As for the others, I'm not sure of the ambiguity is that wrong. I mean, if you like Drama, does it really matter if it's a book or a movie? Or if you speak Spanish or are Spanish?

For me this "Magents Widget" is mostly about making a usually dull page, more playful and interesting.

**Comment by amitaibu** [comment]
Also from technical point - we kept the Magents in same width, so "Speaks Russain" looks bad

**Comment by amitaibu** [comment]
https://github.com/Gizra/gizra-sui/commit/f4c871c123b347ad1a6c848f90dc10586a39cd07

Please re-open if you think it should be addressed differently.
